name: Auto Deploy Hugo Blog
on:
  push:
    branches: [ main ]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库源码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装Hugo 0.164.0扩展版
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.164.0"
          extended: true

      - name: 构建静态网站
        run: hugo --minify

      - name: 自动部署到GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public